const ClientError = require('./ClientError');

/**
 * A class to generate custom error by client
 * @param {*} statusCode=400, generated by parent class
 */
class InvariantError extends ClientError {
  /**
   * @param {*} message error message to be generated
   */
  constructor(message) {
    super(message);
    this.name = 'InvariantError';
  }
}

module.exports = InvariantError;
