const ClientError = require('./ClientError');

/**
 * A class to generate Not Found Error
 * @param {return} statusCode=404, generated by constructor
 */
class NotFoundError extends ClientError {
  /**
   * @param {init} message error to be generated
   */
  constructor(message) {
    super(message, 404);
    this.name = 'NotFoundError';
  }
}

module.exports = NotFoundError;
